### ISSUE TITLE
Error when trying to anaylze .ogg File in Single file Mode

### ISSUE THREAD

**Issue by max-mauermann** [kahst/BirdNET-Analyzer#114]
When selecting an .ogg File to Analyze in Single file Mode (for example from birdclef-2023 dataset) the GUI shows "Error" and the console shows the following Stacktrace.

.ogg Files work without Problems in Multiple files Mode.

```
Traceback (most recent call last):
  File "C:\Users\Max Mauermann\AppData\Roaming\Python\Python310\site-packages\gradio\processing_utils.py", line 142, in audio_from_file
    audio = AudioSegment.from_file(filename)
  File "C:\Users\Max Mauermann\AppData\Roaming\Python\Python310\site-packages\pydub\audio_segment.py", line 728, in from_file
    info = mediainfo_json(orig_file, read_ahead_limit=read_ahead_limit)
  File "C:\Users\Max Mauermann\AppData\Roaming\Python\Python310\site-packages\pydub\utils.py", line 274, in mediainfo_json
    res = Popen(command, stdin=stdin_parameter, stdout=PIPE, stderr=PIPE)
  File "C:\Program Files\Python310\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Python310\lib\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
  File "c:\Users\Max Mauermann\.vscode\extensions\ms-python.python-2023.8.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydev_bundle\pydev_monkey.py", line 901, in new_CreateProcess
    return getattr(_subprocess, original_name)(app_name, cmd_line, *args)
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Max Mauermann\AppData\Roaming\Python\Python310\site-packages\gradio\routes.py", line 412, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\Max Mauermann\AppData\Roaming\Python\Python310\site-packages\gradio\blocks.py", line 1297, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "C:\Users\Max Mauermann\AppData\Roaming\Python\Python310\site-packages\gradio\blocks.py", line 1144, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "C:\Users\Max Mauermann\AppData\Roaming\Python\Python310\site-packages\gradio\components.py", line 2421, in preprocess
    sample_rate, data = processing_utils.audio_from_file(
  File "C:\Users\Max Mauermann\AppData\Roaming\Python\Python310\site-packages\gradio\processing_utils.py", line 152, in audio_from_file
    raise RuntimeError(msg) from e
RuntimeError: Cannot load audio from file: `ffprobe` not found. Please install `ffmpeg` in your system to use non-WAV audio file formats and make sure `ffprobe` is in your PATH.
```

**Comment by Josef-Haupt** [comment]
Works in current repo.
