### ISSUE TITLE
Docker build failure

### ISSUE THREAD

**Issue by dbrianhendrix** [kahst/BirdNET-Analyzer#131]
I am not sure how to deal with the failure below. I have setup a brand new Mac Mini M2 Pro (silicon) and the install / configure instructions from website have worked (conda) until this last part to build the docker container. The default python on the Mac as it came from Apple (Ventura) is "Python 3.10.10".

(birdnet-analyzer) brianhendrix@briMacMiniM2Pro BirdNET-Analyzer % sudo docker build -t birdnetv23 .
[+] Building 0.2s (2/3)
[+] Building 0.2s (3/3) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                         0.0s
 => => transferring dockerfile: 544B                                                                                                                                         0.0s
 => [internal] load .dockerignore                                                                                                                                            0.0s
 => => transferring context: 2B                                                                                                                                              0.0s
 => ERROR [internal] load metadata for docker.io/library/python:3.8-slim                                                                                                     0.2s
------
 > [internal] load metadata for docker.io/library/python:3.8-slim:
------
Dockerfile:2
--------------------
   1 |     # Build from Python 3.8 slim
   2 | >>> FROM python:3.8-slim
   3 |
   4 |     # Install required packages while keeping the image small
--------------------
ERROR: failed to solve: error getting credentials - err: exit status 1, out: ``

**Comment by dbrianhendrix** [comment]
This fixed the issue. Weird!
Edit the file "~/.docker/config.json" and change credsStore to credStore

https://yantonov.com/2021/03/2021-03-06-21-57-docker_error_getting_credentials/

**Comment by dbrianhendrix** [comment]
Well, I thought we were fixed. The build was successful but now I get this:

```
Traceback (most recent call last):
File "analyze.py", line 13, in <module>
import audio
File "/audio.py", line 5, in <module>
import config as cfg
File "/config.py", line 115, in <module>
LABELS: list[str] = []
TypeError: 'type' object is not subscriptable
```

**Comment by dbrianhendrix** [comment]
I've now rebuilt the docker image using V24, and everything works.
