### ISSUE TITLE
Problems with BirdNet Analyzer with python in Mac

### ISSUE THREAD

**Issue by cloaizag81** [kahst/BirdNET-Analyzer#142]
Hello, I was successfully using BirdNet Analyzer in Mac with Python. But today, every code results in: 

Traceback (most recent call last):
  File "/Users/camiloloaizagomez/BirdNET-Analyzer/model.py", line 20, in <module>
    import tflite_runtime.interpreter as tflite
ModuleNotFoundError: No module named 'tflite_runtime'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/camiloloaizagomez/BirdNET-Analyzer/analyze.py", line 15, in <module>
    import model
  File "/Users/camiloloaizagomez/BirdNET-Analyzer/model.py", line 22, in <module>
    from tensorflow import lite as tflite
  File "/Users/camiloloaizagomez/miniconda3/envs/birdnet-analyzer/lib/python3.10/site-packages/tensorflow/__init__.py", line 441, in <module>
    _ll.load_library(_plugin_dir)
  File "/Users/camiloloaizagomez/miniconda3/envs/birdnet-analyzer/lib/python3.10/site-packages/tensorflow/python/framework/load_library.py", line 151, in load_library
    py_tf.TF_LoadLibrary(lib)
tensorflow.python.framework.errors_impl.NotFoundError: dlopen(/Users/camiloloaizagomez/miniconda3/envs/birdnet-analyzer/lib/python3.10/site-packages/tensorflow-plugins/libmetal_plugin.dylib, 0x0006): Symbol not found: (_OBJC_CLASS_$_MPSGraphGRUDescriptor)
  Referenced from: '/Users/camiloloaizagomez/miniconda3/envs/birdnet-analyzer/lib/python3.10/site-packages/tensorflow-plugins/libmetal_plugin.dylib'
  Expected in: '/System/Library/Frameworks/MetalPerformanceShadersGraph.framework/Versions/A/MetalPerformanceShadersGraph'

Can somebody help me with any solution?

Best regards.

**Comment by cloaizag81** [comment]
Hi all, the problem was the Python version, I installed Python 3.11, and the model ran excellently!

Thanks !!!!!

**Comment by shravya0607** [comment]
I'm facing the same issue with py 3.11.4

```py
Traceback (most recent call last):
  File "/Users/jubithrisathi/workspace/BirdNET-Analyzer/model.py", line 20, in <module>
    import tflite_runtime.interpreter as tflite
ModuleNotFoundError: No module named 'tflite_runtime'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jubithrisathi/workspace/BirdNET-Analyzer/analyze.py", line 15, in <module>
    import model
  File "/Users/jubithrisathi/workspace/BirdNET-Analyzer/model.py", line 22, in <module>
    from tensorflow import lite as tflite
  File "/Users/jubithrisathi/miniconda/envs/birdnet-analyzer/lib/python3.11/site-packages/tensorflow/__init__.py", line 441, in <module>
    _ll.load_library(_plugin_dir)
  File "/Users/jubithrisathi/miniconda/envs/birdnet-analyzer/lib/python3.11/site-packages/tensorflow/python/framework/load_library.py", line 151, in load_library
    py_tf.TF_LoadLibrary(lib)
tensorflow.python.framework.errors_impl.NotFoundError: dlopen(/Users/jubithrisathi/miniconda/envs/birdnet-analyzer/lib/python3.11/site-packages/tensorflow-plugins/libmetal_plugin.dylib, 0x0006): Symbol not found: (_OBJC_CLASS_$_MPSGraphGRUDescriptor)
  Referenced from: '/Users/jubithrisathi/miniconda/envs/birdnet-analyzer/lib/python3.11/site-packages/tensorflow-plugins/libmetal_plugin.dylib'
  Expected in: '/System/Library/Frameworks/MetalPerformanceShadersGraph.framework/Versions/A/MetalPerformanceShadersGraph'

```

**Comment by cloaizag81** [comment]
Try consulting ChatGPT!
