### ISSUE TITLE
Modulenotfound Error for TFLite on intel Mac

### ISSUE THREAD

**Issue by N-gardner** [kahst/BirdNET-Analyzer#199]
This is probably something not specific to BirdNET, but when I follow the intel mac instructions, I get the following error when I try to run the python analyze.py (replaced my actual username):

Traceback (most recent call last):
  File "/Users/myuser/BirdNET-Analyzer/model.py", line 21, in <module>
    import tflite_runtime.interpreter as tflite
ModuleNotFoundError: No module named 'tflite_runtime'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/myuser/BirdNET-Analyzer/analyze.py", line 15, in <module>
    import model
  File "/Users/myuser/BirdNET-Analyzer/model.py", line 23, in <module>
    from tensorflow import lite as tflite
  File "/Users/myuser/miniconda3/envs/birdnet-analyzer/lib/python3.10/site-packages/tensorflow/__init__.py", line 441, in <module>
    _ll.load_library(_plugin_dir)
  File "/Users/myuser/miniconda3/envs/birdnet-analyzer/lib/python3.10/site-packages/tensorflow/python/framework/load_library.py", line 151, in load_library
    py_tf.TF_LoadLibrary(lib)
tensorflow.python.framework.errors_impl.NotFoundError: dlopen(/Users/nickgardner/miniconda3/envs/birdnet-analyzer/lib/python3.10/site-packages/tensorflow-plugins/libmetal_plugin.dylib, 0x0006): Symbol not found: (_OBJC_CLASS_$_MPSGraphGRUDescriptor)
  Referenced from: '/Users/myuser/miniconda3/envs/birdnet-analyzer/lib/python3.10/site-packages/tensorflow-plugins/libmetal_plugin.dylib'
  Expected in: '/System/Library/Frameworks/MetalPerformanceShadersGraph.framework/Versions/A/MetalPerformanceShadersGraph'

Does this mean I must separately install the tflite_runtime module? I thought it would have been included in the original package install. 

I have installed and successfully used the analyzer on an M1 mac, I only get this error for a 2015 intel macbook pro.

Any help appreciated!

**Comment by Josef-Haupt** [comment]
I followed the install instructions on a mac and it worked for me. Make sure you install the current tensorflow version (currently 2.15.0)

**Comment by Tindtily** [comment]
same issue

**Comment by Tindtily** [comment]
<img width="367" alt="image" src="https://github.com/kahst/BirdNET-Analyzer/assets/5201107/1f907b0c-439d-4aea-8251-bda796a5dc33">

**Comment by Tindtily** [comment]
Lowering the TensorFlow version to 2.13 resolved it.
According to [tensorflow-metal's description](https://pypi.org/project/tensorflow-metal/)
