### ISSUE TITLE
Error Training with Use Autotune Selected (Gui v 1.0.0-beta1)

### ISSUE THREAD

**Issue by reedflyfarm** [kahst/BirdNET-Analyzer#265]
Training fails with error when training on once class of 1000 files (bandpass 250 - 3000)

Traceback (most recent call last):
  File "gui.py", line 14, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "librosa\__init__.py", line 209, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "librosa\core\__init__.py", line 6, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "librosa\core\audio.py", line 11, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "scipy\signal\__init__.py", line 331, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "scipy\signal\_peak_finding.py", line 8, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "scipy\stats\__init__.py", line 485, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "scipy\stats\_stats_py.py", line 46, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "scipy\stats\distributions.py", line 10, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "scipy\stats\_continuous_distns.py", line 32, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "scipy\stats\_boost\__init__.py", line 13, in <module>
ImportError: DLL load failed while importing nbinom_ufunc: The paging file is too small for this operation to complete.

**Comment by kahst** [comment]
We had a few dynamic resource allocation issues and some version mismatches, but this should be resolved in the 1.0.2 release. Can you please check?

**Comment by reedflyfarm** [comment]
Will do. This is my first time with the installer. Do I need to uninstall and reinstall or just install over top.

**Comment by reedflyfarm** [comment]
that worked
