### ISSUE TITLE
Error using segments.py and multiple threads

### ISSUE THREAD

**Issue by jimmyknowles** [kahst/BirdNET-Analyzer#31]
It appears that when using multiple threads, there are some timing issues with directory creation. When I use multiple threads, I get multiple errors that are like:

`Error: Cannot extract segments from e:\audio\20220427_081956.WAV.
Traceback (most recent call last):
  File "D:\Downloads\BirdNET-Analyzer-main\BirdNET-Analyzer-main\segments.py", line 188, in extractSegments
    os.makedirs(outpath)
  File "C:\Users\jknowles\AppData\Local\ESRI\conda\envs\clone3\lib\os.py", line 223, in makedirs
    mkdir(name, mode)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'e:\\segments_0_80\\Virginia Rail'`

I think what is happening is that lines 187 and 188 in segments.py are being run concurrently in separate threads that are causing the os to try and create a directory that was already created in a different thread.

`               if not os.path.exists(outpath):`
`                    os.makedirs(outpath)`

Potential solution would be to go through and create all the species directories first before using Pool to run extractSegments in multiple threads.

I was able to successfully run segments.py without any errors using --threads set to 1.

**Comment by kahst** [comment]
Good catch, that seems to be an issue. `os.makedirs` does have a flag `exist_ok` which we can set to `True`, that should solve the issue. All push an update. Can you try again after that?

**Comment by jimmyknowles** [comment]
I see you've already made the commit, so I'll download and test on the same dataset that caused the error.

**Comment by jimmyknowles** [comment]
Worked like a charm on both segments.py and analyze.py. Thanks!
