### ISSUE TITLE
Cannot utilize PBMODEL

### ISSUE THREAD

**Issue by DengXuyao** [kahst/BirdNET-Analyzer#327]
**This is my codes:**

import tensorflow as tf
PBMODEL = tf.keras.models.load_model('/home/dxy/桌面/BirdNET-Analyzer-main/checkpoints/V2.4/BirdNET_GLOBAL_6K_V2.4_Model/', compile=False)
random_data = np.random.rand(32, 144000)
print(PBMODEL.embeddings_model(random_data))

**When I run, I meet error:**
Traceback (most recent call last):
  File "/home/dxy/桌面/BirdNET-Analyzer-main/test.py", line 20, in <module>
    print(PBMODEL.embeddings_model(random_data))
  File "/home/dxy/anaconda3/envs/bird_net/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/dxy/anaconda3/envs/bird_net/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 5888, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InternalError: Exception encountered when calling layer 'BNORM_SPEC_NOQUANT' (type BatchNormalization).

{{function_node __wrapped__FusedBatchNormV3_device_/job:localhost/replica:0/task:0/device:GPU:0}} cuDNN launch failure : input shape ([32,96,511,2]) [Op:FusedBatchNormV3] name: 

Call arguments received by layer 'BNORM_SPEC_NOQUANT' (type BatchNormalization):
  • inputs=tf.Tensor(shape=(32, 96, 511, 2), dtype=float32)
  • training=None
  • mask=None

**It seems that the layer 'BNORM_SPEC_NOQUANT'  can't work, how can I solve this problem?**

**Comment by DengXuyao** [comment]
I have solved this problem. The layer 'BNORM_SPEC_NOQUANT' can't work on CUDA, and my tensorflow support CUDA in default, so just disable GPU when use tensorflow. like this:

**tf.config.set_visible_devices([], 'GPU')**
PBMODEL = tf.keras.models.load_model('/home/dxy/桌面/BirdNET-Analyzer-main/checkpoints/V2.4/BirdNET_GLOBAL_6K_V2.4_Model/', compile=False)
random_data = np.random.rand(32, 144000)
print(PBMODEL.embeddings_model(random_data))
