### ISSUE TITLE
Missing tensorflow - MacOS M1

### ISSUE THREAD

**Issue by kevtolan** [kahst/BirdNET-Analyzer#345]
Hello,

I've been able to install/use BirdNET in the past, but am running into difficulties this time around.

**Computer**: 2021 M1 Macbook Pro 
**OS**: Sonoma 14.4.1
**Other details**: Fresh install of xcode

**To Reproduce**
1. Follow the [macOS setup instructions](https://github.com/kahst/BirdNET-Analyzer?tab=readme-ov-file#setup-macos), running in Terminal.
2. Run "python analyze.py", as per instructions
3. Receive the following error:

```
(venv-birdnet) (base) ktol@KTolVCE BirdNET-Analyzer % python analyze.py
Traceback (most recent call last):
  File "/Users/kevintolan/BirdNET-Analyzer/model.py", line 21, in <module>
    import tflite_runtime.interpreter as tflite
ModuleNotFoundError: No module named 'tflite_runtime'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kevintolan/BirdNET-Analyzer/analyze.py", line 17, in <module>
    import model
  File "/Users/kevintolan/BirdNET-Analyzer/model.py", line 23, in <module>
    from tensorflow import lite as tflite
ImportError: cannot import name 'lite' from 'tensorflow' (unknown location)
```

I've had no luck installing tflite-runtime seperately:
```
(venv-birdnet) (base) ktol@KTolVCE BirdNET-Analyzer % python -m pip install tflite-runtime

Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement tflite-runtime (from versions: none)
ERROR: No matching distribution found for tflite-runtime
```

The error also indicates that the system can't find tensorflow, despite it being downloaded  in the instructions:
```python -m pip install tensorflow==2.15.0 tensorflow-metal```

I've also tried downloading tensorflow-macos, but that hasn't helped. 
```python -m pip install tensorflow-macos```

I'm hoping for any thoughts as to why the system isn't recognizing tensorflow, or what dependencies I'm missing?

Thanks!
Kevin

**Comment by Josef-Haupt** [comment]
Could be an environment problem, check `pip list` output.

**Comment by kevtolan** [comment]
I had to remove the `python -m` to install them successfully into the `pip list`, otherwise they weren't downloading into the venv. tf-metal is having issues downloading.

```
(venv-birdnet) (base) ktol@KTolVCE BirdNET-Analyzer % pip install tensorflow==2.15.0 tensorflow-metal

Collecting tensorflow==2.15.0
  Using cached tensorflow-2.15.0-cp39-cp39-macosx_10_15_x86_64.whl.metadata (4.2 kB)
ERROR: Could not find a version that satisfies the requirement tensorflow-metal (from versions: none)
ERROR: No matching distribution found for tensorflow-metal
```

Here's the pip list
```
(venv-birdnet) (base) ktol@KTolVCE BirdNET-Analyzer % pip list
Package                      Version
---------------------------- ------------
absl-py                      2.1.0
astunparse                   1.6.3
audioread                    3.0.1
certifi                      2024.2.2
cffi                         1.16.0
charset-normalizer           3.3.2
decorator                    5.1.1
flatbuffers                  24.3.25
gast                         0.5.4
google-pasta                 0.2.0
grpcio                       1.64.0
h5py                         3.11.0
idna                         3.7
importlib_metadata           7.1.0
joblib                       1.4.2
keras                        3.3.3
lazy_loader                  0.4
libclang                     18.1.1
librosa                      0.10.2.post1
llvmlite                     0.42.0
Markdown                     3.6
markdown-it-py               3.0.0
MarkupSafe                   2.1.5
mdurl                        0.1.2
ml-dtypes                    0.3.2
msgpack                      1.0.8
namex                        0.0.8
numba                        0.59.1
numpy                        1.26.4
opt-einsum                   3.3.0
optree                       0.11.0
packaging                    24.0
pip                          24.0
platformdirs                 4.2.2
pooch                        1.8.1
protobuf                     4.25.3
pycparser                    2.22
Pygments                     2.18.0
requests                     2.32.3
resampy                      0.4.3
rich                         13.7.1
scikit-learn                 1.5.0
scipy                        1.13.1
setuptools                   58.1.0
six                          1.16.0
soundfile                    0.12.1
soxr                         0.3.7
tensorboard                  2.16.2
tensorboard-data-server      0.7.2
tensorflow                   2.16.1
tensorflow-io-gcs-filesystem 0.37.0
termcolor                    2.4.0
threadpoolctl                3.5.0
typing_extensions            4.12.0
urllib3                      2.2.1
Werkzeug                     3.0.3
wheel                        0.43.0
wrapt                        1.16.0
zipp                         3.19.0
```

I'm still getting the same error when trying again:
```
(venv-birdnet) (base) ktol@KTolVCE BirdNET-Analyzer % python analyze.py

Traceback (most recent call last):
  File "/Users/kevintolan/BirdNET-Analyzer/model.py", line 21, in <module>
    import tflite_runtime.interpreter as tflite
ModuleNotFoundError: No module named 'tflite_runtime'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kevintolan/BirdNET-Analyzer/analyze.py", line 17, in <module>
    import model
  File "/Users/kevintolan/BirdNET-Analyzer/model.py", line 23, in <module>
    from tensorflow import lite as tflite
ImportError: cannot import name 'lite' from 'tensorflow' (unknown location)
(venv-birdnet) (base) ktol@KTolVCE BirdNET-Analyzer % 
```

**Comment by Josef-Haupt** [comment]
First of all, we are currently only supporting TF 2.15.x, there are breaking changes when upgrading to TF 2.16 which you are currently using.
Here is a simple check, activate you environment, start the python interpreter (just `python`), enter `import sys; sys.executable`, is the python executable on the correct directory? Then enter `import tensorflow as tf`, see if that works, if so check `tf.lite`.
All of these should work if tensorflow is installed correctly in your chosen environment.

**Comment by kevtolan** [comment]
I downgraded to TF 2.15.0. Python appears to be correctly placed.

```
>>> import sys; sys.executable
'/Library/Developer/CommandLineTools/usr/bin/python3'
```

`import tensorflow as tf` works fine, but I'm still missing `tf.life` from the venv. 

```
>>> import tensorflow as tf
>>> tf.lite
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'tensorflow' has no attribute 'lite'
```

**Comment by kevtolan** [comment]
I solved the problem by using Anaconda Navigator, and needed to install tflite_runtime using ([via Stack](https://stackoverflow.com/questions/74968761/pip3-cant-download-the-latest-tflite-runtime)):

`pip3 install --extra-index-url https://google-coral.github.io/py-repo/ tflite_runtime
`
