### ISSUE TITLE
BirdNET-Analyzer GUI throws an error and closes (Windows installer v1.2)

### ISSUE THREAD

**Issue by DD4WH** [kahst/BirdNET-Analyzer#375]
After installing and starting the Windows Installer v1.2 the GUI window opens, throws an error and closes.

**To Reproduce**
1. Installed v1.2.0 on Windows
2. Clicked on BirdNET Analyzer icon to start the program
3. Error:
Traceback (most recent call last):
  File "gui.py", line 1681, in <module>
  File "C:\Users\DD4WH\AppData\Local\Programs\BirdNET-Analyzer\_internal\gradio\blocks.py", line 2375, in launch
    raise ValueError(
ValueError: When localhost is not accessible, a shareable link must be created. Please set share=True or check your proxy settings to allow access to localhost.

4. Program closes

![grafik](https://github.com/kahst/BirdNET-Analyzer/assets/14326464/7418308f-d0ee-41e9-9033-7abeed697871)

**Comment by Accurio** [comment]
If you use a proxy server in Windows, you may need to set `HTTP_PROXY`,  `HTTPS_PROXY` and `NO_PROXY` environment variables. Open a command prompt, run this code, set the environment variables and start BirdNET Analyzer from the command prompt.

```
set http_proxy=<proxy-server-url>
set https_proxy=<proxy-server-url>
set no_proxy=localhost,127.0.0.1,::1
start "" <BirdNET-Analyzer-path>
```

**Comment by Josef-Haupt** [comment]
Yes, Gradio opens up a local webserver, but localhost does not seem to be accessible on you pc for some reason. The setting the proxy resolve the problem?

**Comment by DD4WH** [comment]
with the latest version of the Windows Installer the issue seems to be gone! Thank you!
