### ISSUE TITLE
gui.py fails with IsADirectoryError

### ISSUE THREAD

**Issue by ceperman** [kahst/BirdNET-Analyzer#412]
When analyzing an mp3 file, gui.py fails with error msg:

`IsADirectoryError: [Errno 21] Is a directory: '/tmp/gradio/..../ENC0007-songt-greenp-short.csv'`

This is the culmination of a long and error-strewn process of installing BirdNET-Analyzer on Linux Mint 20.3! The main issue was that I needed to upgrade Python from 3.8 to 3.10. This entailed lots of trail and error to get the required components installed and at the right level. I think I got there eventually although I'm willing to believe that the problem is likely something I've done (or not done).

The problem happens with any file I try.

Terminal output:

```
chris@Home:~/BirdNET-Analyzer$ python3.10 gui.py
[pywebview] GTK cannot be loaded
Traceback (most recent call last):
  File "/home/chris/.local/lib/python3.10/site-packages/webview/guilib.py", line 37, in import_gtk
    import webview.platforms.gtk as guilib
  File "/home/chris/.local/lib/python3.10/site-packages/webview/platforms/gtk.py", line 21, in <module>
    import gi
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 42, in <module>
    from . import _gi
ImportError: cannot import name '_gi' from partially initialized module 'gi' (most likely due to a circular import) (/usr/lib/python3/dist-packages/gi/__init__.py)
js: Attempted to select a non-interactive or hidden tab.
js: Attempted to select a non-interactive or hidden tab.
js: Too many arguments provided for the endpoint.
js: Method not implemented.
js: Too many arguments provided for the endpoint.
js: Method not implemented.
js: Too many arguments provided for the endpoint.
js: Too many arguments provided for the endpoint.
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
Species list contains 220 species
Analyzing /tmp/gradio/1de465d1a60c5193e3f91c1e8bff25f87c730cca8b2abe0d573b6eb2dd369eb3/ENC0007-songt-greenp-short.mp3
WARNING: Attempting to use a delegate that only supports static-sized tensors with a graph that has dynamic-sized tensors (tensor#187 is a dynamic-sized tensor).
Finished /tmp/gradio/1de465d1a60c5193e3f91c1e8bff25f87c730cca8b2abe0d573b6eb2dd369eb3/ENC0007-songt-greenp-short.mp3 in 4.95 seconds
Traceback (most recent call last):
  File "/home/chris/.local/lib/python3.10/site-packages/gradio/queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "/home/chris/.local/lib/python3.10/site-packages/gradio/route_utils.py", line 288, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/chris/.local/lib/python3.10/site-packages/gradio/blocks.py", line 1941, in process_api
    data = await self.postprocess_data(block_fn, result["prediction"], state)
  File "/home/chris/.local/lib/python3.10/site-packages/gradio/blocks.py", line 1764, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "/home/chris/.local/lib/python3.10/site-packages/gradio/components/dataframe.py", line 263, in postprocess
    value = pd.read_csv(value)  # type: ignore
  File "/home/chris/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/chris/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/chris/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/chris/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "/home/chris/.local/lib/python3.10/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
IsADirectoryError: [Errno 21] Is a directory: '/tmp/gradio/1de465d1a60c5193e3f91c1e8bff25f87c730cca8b2abe0d573b6eb2dd369eb3/ENC0007-songt-greenp-short.csv
chris@Home:~/BirdNET-Analyzer$
```
I figured that the import error for gi may not be important as I'm using Qt not GTK.

**Comment by Josef-Haupt** [comment]
Installing in Linux is tricky, but it does work after some extra install step.
I can't really say what went wrong in your case. Looking at the path, it seems like there was an error with gradio, since it creates some temporary files an directories.

**Comment by ceperman** [comment]
Don't know if this could be the same issue: https://github.com/gradio-app/gradio/issues/8265
... just because @sachin-aakash indicated his/her code was working before they upgraded gradio to the latest version.

My gradio==4.41.0

**Comment by max-mauermann** [comment]
This was most likely a bug on our side, caused by how we save the .csv file that is shown in the GUI.
It should be fixed with the pull request

**Comment by ceperman** [comment]
That fixes it, thanks.
