### ISSUE TITLE
The Windows package for BirdNET-Analyzer 1.3.1 cannot open after being installed for all users

### ISSUE THREAD

**Issue by msp2** [kahst/BirdNET-Analyzer#475]
After I installing the Windows package for BirdNET-Analyzer 1.3.1 in Windows 11, BirdNET-Analyzer cannot open. When I attempt to do so, an error dialog pops up saying the following:

> Unhandled exception in script
> 
> Failed to excecute script 'gui' due to unhandled exception: [Errno 13] Permission denied: 'C:\\Program Files (x86)\\BirdNET-Analyzer\\_internal\\gui-settings.json'
> 
> Traceback (most recent call last):
>   File "gui.py", line 46, in <module>
>   File "localization.py", line 46, in load_local_state
>   File "localization.py", line 15, in ensure_settings_file
> PermissionError: [Errno 13] Permission denied: 'C:\\Program Files (x86)\\BirdNET-Analyzer\\_internal\\gui-settings.json'

**Comment by tphakala** [comment]
Uninstall and install using "Install for me only" option and it works

**Comment by Josef-Haupt** [comment]
Did reinstalling solve your problem?
