### ISSUE TITLE
numpy error initializing an empty array

### ISSUE THREAD

**Issue by thk686** [kahst/BirdNET-Analyzer#477]
I watched this run using `htop` and memory usage never exceeded 600MB out of 3.7GB. These are 15 minute continuous recordings. Can I ignore these or is it limiting the output in some way?

```
2024-10-22 17:55:15,532 - ERROR - Error: Generic audio read error occurred from librosa. in /home/biosense/datastore/sound_recordings/arecord_biosense_1_3_26_176886N_98_228964W_20240919_230419-2869.flac
2024-10-22 17:55:15,535 - ERROR - Traceback: Traceback (most recent call last):
  File "/home/biosense/biosense_venv/lib/python3.11/site-packages/birdnetlib/main.py", line 311, in read_audio_data
    self.ndarray, rate = librosa.load(
                         ^^^^^^^^^^^^^
  File "/home/biosense/biosense_venv/lib/python3.11/site-packages/librosa/core/audio.py", line 176, in load
    y, sr_native = __soundfile_load(path, offset, duration, dtype)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/biosense/biosense_venv/lib/python3.11/site-packages/librosa/core/audio.py", line 222, in __soundfile_load
    y = sf_desc.read(frames=frame_duration, dtype=dtype, always_2d=False).T
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/biosense/biosense_venv/lib/python3.11/site-packages/soundfile.py", line 891, in read
    out = self._create_empty_array(frames, always_2d, dtype)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/biosense/biosense_venv/lib/python3.11/site-packages/soundfile.py", line 1323, in _create_empty_array
    return np.empty(shape, dtype, order='C')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: array is too big; `arr.size * arr.dtype.itemsize` is larger than the maximum possible size.
```

**Comment by thk686** [comment]
It was a corrupted file.
