### ISSUE TITLE
No splash screen on Mac version and very long launch time

### ISSUE THREAD

**Issue by Mattk70** [kahst/BirdNET-Analyzer#495]
**Describe the bug**
The splash screen fails to appear when launching the Mac version. Also the application takes 85 seconds to open on my M2 Macbook pro.

**Expected behavior**
Splash screen should appear, and launch should be no more than a few seconds.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS, Win10] Moc OSX  (Sequoia) 15.0.1 (24A348)
 - Version [e.g. 1.0.2]: 1.3.1

**Additional context**
The launch delay is not just the first time the app is launched, but every time.

Logs has an error: 

Matplotlib is building the font cache; this may take a moment.
The environment does not allow connecting to the splash screen. Did bootloader fail to initialize it?
Traceback (most recent call last):
  File "PyInstaller/fake-modules/pyi_splash.py", line 108, in <module>
  File "os.py", line 680, in __getitem__
KeyError: '_PYI_SPLASH_IPC'
Species list contains 6522 species
Analyzing /private/var/folders/v1/wnmz5lrn48n7nbcdmgxj29rr0000gn/T/gradio/a9d7e32f7601821f0f9d5b4ae9eee135a06019ec59e5aa027fe3fb115c1f3ecb/210331_0402.wav
Finished /private/var/folders/v1/wnmz5lrn48n7nbcdmgxj29rr0000gn/T/gradio/a9d7e32f7601821f0f9d5b4ae9eee135a06019ec59e5aa027fe3fb115c1f3ecb/210331_0402.wav in 135.63 seconds

**Comment by Josef-Haupt** [comment]
Sadly, the splash screen is a Win only feature. It's part of pyinstaller, which we use to bundle the app and it currently only supports windows (see [here](https://pyinstaller.org/en/stable/usage.html#splash-screen-experimental))

**Comment by Mattk70** [comment]
Thanks, @Josef-Haupt . If that's the case, is there no way you could get the program to load faster? To have to wait nearly a minute and a half after pressing the launch icon before there's any indication that the app is firing up is a problem, I'd say.

**Comment by tphakala** [comment]
Application start is very slow on high end Windows PC as well, I guess it has nothing to do with splash screen

**Comment by Josef-Haupt** [comment]
Seems like the bundling process adds a LOT of startup time. It's hard to say what exactly is taking so long. Direkt startup with python is actually very fast on win and mac too. That is why I initially added the splash screen, so users can atleast see, that work is being done. But on Mac it currently looks like the startup failed because it takes so long. I'll do some testing, maybe there is something to be done, without switching tools.
