### ISSUE TITLE
GUI install not working - error about GTK/QT 

### ISSUE THREAD

**Issue by carlybatist** [kahst/BirdNET-Analyzer#56]
I am having trouble getting the GUI to load. I input the exact commands on the page for Ubuntu setup, and then the `pip install pywebview` and `python gui.py` commands but I am getting this error. I tried doing `pip install pywebview[qt]` and this also does not work. I am doing this SSH'd into an Azure virtual machine (Ubuntu Data Science 20.04 image). 

I would try it on my laptop but I have a Mac and I don't see install instructions for MacOS so not sure if it is supported (please let me know otherwise). The BirdNet website is down at the moment as well so I can't access it from there either. 

```
azureuser@lemurprayers:/datadrive/BirdNET-Analyzer$ python gui.py
[pywebview] GTK cannot be loaded
Traceback (most recent call last):
  File "/anaconda/lib/python3.9/site-packages/webview/guilib.py", line 16, in import_gtk
    import webview.platforms.gtk as guilib
  File "/anaconda/lib/python3.9/site-packages/webview/platforms/gtk.py", line 26, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
[pywebview] Using Qt 5.15.2
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Aborted (core dumped)
(base) azureuser@lemurprayers:/datadrive/BirdNET-Analyzer$
```

**Comment by Josef-Haupt** [comment]
This seems to be an issue with the gtk installation on your machine. The current gui is based on the `pywebview` package, which uses a different library based on your OS and installed libraries, this can lead to a variety of problems.

Since we are going to switch to [Gradio](https://gradio.app/) in the near future, I will close this issue.

**Comment by kdarras** [comment]
I have the same problem.
Followed the instructions for Ubuntu setup to install all dependencies and clone the repo inside a virtual environment.
After pip-installing pywebaudio and gradio, I tried launching the GUI and got:
`webview.util.WebViewException: You must have either QT or GTK with Python extensions installed in order to use pywebview`

I solved it by running `pip install qtpy pyside2`
However, now, after trying to launch the GUI, a blank GUI shows up and I get:
`ModuleNotFoundError: No module named 'gi'
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.`

So I followed [this](https://askubuntu.com/questions/80448/what-would-cause-the-gi-module-to-be-missing-from-python) and tried:
`pip install vext
pip install vext.gi`
Which got me an error:
`ERROR: Could not build wheels for vext.gi, which is required to install pyproject.toml-based projects`

Then I tried:
`sudo apt install pkg-config libcairo2-dev gcc python3-dev libgirepository1.0-dev
pip install PyGObject`
But it produces this now when launching the GUI:
`(gui.py:20272): GLib-GIO-ERROR **: 21:52:27.028: Settings schema 'org.appmenu.gtk-module' is not installed
Trace/breakpoint trap (core dumped)`

**Comment by kdarras** [comment]
Finally got it to work by following up on the last error with the advice found [here](https://askubuntu.com/questions/1346576/how-to-fix-glib-gio-error-settings-schema-org-gtk-settings-filechooser-is-not):
`sudo apt-get update
sudo apt-get install --reinstall libgtk-3-common`
